apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
  namespace: sns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: spring-app-logs
      containers:
        - name: user-container
          image: {{AWS_ACCOUNT_ID}}.dkr.ecr.{{AWS_REGION}}.amazonaws.com/{{ECR_USER_SERVER_REPO}}:${IMAGE_TAG}
          volumeMounts:
            - name: logs
              mountPath: /logs
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
            - configMapRef:
                name: kafka-config
            - secretRef:
                name: kafka-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 10"]
          readinessProbe:
            httpGet:
              path: /healthcheck/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 1
            failureThreshold: 7
