apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-server
  namespace: sns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: image-server
  template:
    metadata:
      labels:
        app: image-server
    spec:
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: image-volume-claim
      containers:
        - name: image
          image: {{AWS_ACCOUNT_ID}}.dkr.ecr.{{AWS_REGION}}.amazonaws.com/{{ECR_IMAGE_SERVER_REPO}}:${IMAGE_TAG}
          volumeMounts:
            - name: image-volume
              mountPath: /images
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: IMAGE_PATH
              value: images
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "700m"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 10"]
          readinessProbe:
            httpGet:
              path: /healthcheck/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 1
            failureThreshold: 7
            